parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: ipw
    database_user: ipw
    database_password: Ryinlet8
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 911ee000a9742e55d26fbaecb97c02de79435edb
