parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: IPW
    database_user: ipw
    database_password: ipw
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 57ed7c7982737a7afde68de5a694a0330e8cf7f7
