parameters:
#    unsapa_ipw.example.class: Unsapa\IPWBundle\Example

services:
#    unsapa_ipw.example:
#        class: %unsapa_ipw.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
