parameters:
#    unsapa_ipw.example.class: Unsapa\IPWBundle\Example

services:
#    unsapa_ipw.example:
#        class: %unsapa_ipw.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    unsapa_user.registration.form.type:
        class: Unsapa\IPWBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }
